FROM ubuntu:14.04
MAINTAINER  Eboox "dev@eboox.it"

RUN apt-get update && apt-get install -y wget

ADD conf/smile-magento-elasticsearch/scripts/install /scripts

EXPOSE 9200
EXPOSE 9300

RUN chmod +x /scripts/install-es.sh
RUN ["/scripts/install-es.sh","eboox", "127.0.0.1:9200"]

CMD /etc/init.d/elasticsearch start && /bin/sh -c "while true; do sleep 10; done"